CREATE TABLE ACCOUNTS (
ACCOUNT_ID NUMBER,
ACCOUNT_BALANCE DOUBLE,
USER_ID NUMBER
);

CREATE TABLE BANK_USERS (
USER_NAME VARCHAR2(20),
USER_PASSWORD VARCHAR2(20),
IS_ADMIN NUMBER
);

CREATE TABLE USER_ACCOUNT (
NAME VARCHAR2(20),
ID NUMBER
);

COMMIT;