CREATE TABLE SUPERHERO(
HEROID INTEGER PRIMARY KEY,
HERONAME VARCHAR2(30)
);

CREATE TABLE POWERS (
POWERID INT PRIMARY KEY,
POWERNAME VARCHAR2(30)
);

CREATE SEQUENCE HEROSEQ;
CREATE SEQUENCE POWSEQ;

INSERT INTO SuperHero VALUES (HEROSEQ.NEXTVAL, 'PegaMan');
COMMIT;

CREATE OR REPLACE PROCEDURE InserSuperHero(NAME IN VARCHAR2)
AS
BEGIN
    INSERT INTO SuperHero VALUES(HEROSEQ.NEXTVAL,Name);
    COMMIT;
END;
/
